return function(lyrics, idx, f)
    local lyricList, phonemeList = {}, {}
    local def = idx == 2 and "u:" or "a"
    local dict={ -- English,Korean,Spanish,Chinese,Maika,SeeU
        a={"V","a","a","a","a","a"},
        i={"i:","i","i","i","i","i"},
        u={"u:","M","u","u","u","M"},
        e={"e","e","e","ei","e","e"},
        o={"O:","o","o","o","o","o"},
        ka={"kh V","k a","k a","k_h a","k a","k a"},
        ki={"kh i:","k i","k i","k_h 7 i","k i","k i"},
        ku={"kh U","k M","k u","k_h u","k u","k M"},
        ke={"kh e","k e","k e","k_h ei","k e","k e"},
        ko={"kh O:","k o","k o","k_h @U","k o","k o"},
        sa={"s V","s a","s a","s a","s a","s a"},
        shi={"S i:","sh i","s j i","s\\ i","S i","sh i"},
        su={"s U","s M","s u","s u","s u","s M"},
        se={"s e","s e","s e","s ei","s e","s e"},
        so={"s O:","s o","s o","s @U","s o","s o"},
        ta={"th V","t a","t a","t_h a","t a","t a"},
        chi={"tS i:","ch i","tS i","ts\\_h i","tS i","ch i"},
        tsu={"t s u:","ch M","t s u","ts_h u","ts u","ch M"},
        te={"th e","t e","t e","t_h ei","t e","t e"},
        to={"th @U","t o","t o","t_h @U","t o","t o"},
        na={"n V","n a","n a","n a","n a","n a"},
        ni={"n i:","n i","J i","n i","J i","n i"},
        nu={"n U","n M","n u","n u","n u","n M"},
        ne={"n e","n e","n e","n ei","n e","n e"},
        no={"n O:","n o","n o","n @U","n o","n o"},
        ha={"h V","h a","x a","x a","h a","h a"},
        hi={"h i:","h i","x i","x 7 i","h i","h i"},
        fu={"f U","h M","f u","f u","f u","f M"},
        he={"h e","h e","x e","x ei","h e","h e"},
        ho={"h O:","h o","x o","x @U","h o","h o"},
        ma={"m V","m a","m a","m a","m a","m a"},
        mi={"m i:","m i","m i","m i","m i","m i"},
        mu={"m U","m M","m u","m u","m u","m M"},
        me={"m e","m e","m e","m ei","m e","m e"},
        mo={"m O:","m o","m o","m o","m o","m o"},
        ra={"l0 V","r a","r a","l a","r a","r a"},
        ri={"l0 i:","r i","r i","l i","r i","r i"},
        ru={"l0 u:","r M","r u","l u","r u","r M"},
        re={"l0 e","r e","r e","l ei","r e","r e"},
        ro={"l0 O:","r o","r o","l o","r o","r o"},
        ga={"gh V","g a","g a","k a","g a","g a"},
        gi={"gh i:","g i","g i","k 7 i","g i","g i"},
        gu={"gh U","g M","g u","k u","g u","g M"},
        ge={"gh e","g e","g e","k ei","g e","g e"},
        go={"gh O:","g o","g o","k @U","g o","g o"},
        za={"z V","c a","D s a","ts a","dz a","z a"},
        ji={"dZ i:","c i","D j i","ts\\ i","dZ i","z i"},
        zu={"z U","c M","D s u","ts u","dz u","z M"},
        ze={"z e","c e","D s e","ts ei","dz e","z e"},
        zo={"z O:","c o","D s o","ts @U","dz o","z o"},
        de={"dh e","d e","d e","t ei","d e","d e"},
        ["do"]={"dh O:","d o","d o","t @U","d o","d o"},
        ba={"bh V","b a","b a","p a","b a","b a"},
        bi={"bh i:","b i","b i","p i","b i","b i"},
        bu={"bh U","b M","b u","p u","b u","b M"},
        be={"bh e","b e","b e","p ei","b e","b e"},
        bo={"bh O:","b o","b o","p o","b o","b o"},
        pa={"ph V","p a","p a","p_h a","p a","p a"},
        pi={"ph i:","p i","p i","p_h i","p i","p i"},
        pu={"ph U","p M","p u","p_h u","p u","p M"},
        pe={"ph e","p e","p e","p_h ei","p e","p e"},
        po={"ph O:","p o","p o","p_h o","p o","p o"},
        ya={"j V","ja","j a","ia","j a","ja"},
        yu={"j U","ju","j u","i@U","j u","ju"},
        yo={"j O:","jo","j o","iAU","j o","jo"},
        wa={"w V","oa","w a","ua","w a","oa"},
        wi={"w i:","ui","w i","u i","w i","ui"},
        we={"w e","ue","w e","uei","w e","ue"},
        wo={"w O:","u7","w o","uo","w o","u7"},
        fa={"f V","h a","f a","f a","f a","f a"},
        tsa={"t s V","ch a","t s a","ts_h a","ts a","ch a"},
        si={"s i:","s i","s i","s i\\ i","s i","s i"},
        zi={"z i:","c i","D s i","ts i\\ i","dz i","z i"},
        tsi={"t s i:","ch i","t s i","ts_h i\\ i","ts i","ch i"},
        ti={"th i:","t i","t i","t_h i","t i","t i"},
        di={"dh i:","d i","d i","t i","d i","d i"},
        fi={"f i:","h i","f i","f o i","f i","f i"},
        tu={"th U","t M","t u","t_h u","t u","t M"},
        du={"dh U","d M","d u","t u","d u","d M"},
        ye={"j e","je","j e","iE_r","j e","je"},
        kye={"kh j e","k je","k j e","k_h 7 iE_r","k j e","k je"},
        she={"S e","sh je","s j e","s\\ iE_r","S e","sh je"},
        che={"tS e","ch je","tS e","ts\\_h iE_r","tS e","ch e"},
        tse={"t s e","ch e","t s e","ts_h 7 ei","ts e","ch e"},
        nye={"n j e","n je","J e","n iE_r","J e","n je"},
        hye={"h j e","h je","x j e","x 7 iE_r","h j e","h je"},
        mye={"m j e","m je","m j e","m iE_r","m j e","m je"},
        rye={"l0 j e","r je","r j e","l iE_r","r j e","r je"},
        gye={"gh j e","g je","G j e","k 7 iE_r","G j e","g je"},
        je={"dZ e","c e","D j e","ts\\ iE_r","dZ e","z e"},
        bye={"bh j e","b je","b j e","p iE_r","b j e","b je"},
        fe={"f e","h e","f e","f ei","f e","f e"},
        tso={"t s O:","ch o","t s o","ts_h @U","ts o","ch o"},
        fo={"f O:","h o","f o","f o","f o","f o"},
        kya={"kh j V","k ja","k j a","k_h 7 ia","k j a","k ja"},
        sha={"S V","sh ja","s j a","s\\ ia","S a","sh ja"},
        cha={"tS V","ch ja","tS a","ts\\_h ia","tS a","ch a"},
        nya={"n j V","n ja","J a","n i a","J a","n ja"},
        hya={"h j V","h ja","x j a","x 7 ia","h j a","h ja"},
        mya={"m j V","m ja","m j a","m i a","m j a","m ja"},
        rya={"l0 j V","r ja","r j a","l ia","r j a","r ja"},
        gya={"gh j V","g ja","G j a","k 7 ia","G j a","g ja"},
        ja={"dZ V","c a","D j a","ts\\ ia","dZ a","z a"},
        bya={"bh j V","b ja","b j a","p i a","b j a","b ja"},
        pya={"p j V","p ja","p j a","p_h i a","p j a","p ja"},
        kyu={"kh j U","k ju","k j u","k_h 7 i@U","k j u","k ju"},
        shu={"S U","sh ju","s j u","s\\ i@U","S u","sh ju"},
        chu={"tS U","ch ju","tS u","ts\\_h i@U","tS u","ch M"},
        nyu={"n j U","n ju","J u","n i@U","J u","n ju"},
        hyu={"h j U","h ju","x j u","x 7 i@U","h j u","h ju"},
        myu={"m j U","m ju","m j u","m i@U","m j u","m ju"},
        ryu={"l0 j U","r ju","r j u","l i@U","r j u","r ju"},
        gyu={"gh j U","g ju","G j u","k 7 i@U","G j u","g ju"},
        ju={"dZ U","c M","D j u","ts\\ i@U","dZ u","z M"},
        byu={"bh j U","b ju","b j u","p i @U","b j u","b ju"},
        pyu={"p j U","p ju","p j u","p_h i @U","p j u","p ju"},
        kyo={"kh j O:","k jo","k j o","k_h 7 iAU","k j o","k jo"},
        sho={"S O:","sh jo","s j o","s\\ iAU","S o","sh jo"},
        cho={"tS O:","ch jo","tS o","ts\\_h iAU","tS o","ch o"},
        nyo={"n j O:","n jo","J o","n iAU","J o","n jo"},
        hyo={"h j O:","h jo","x j o","x 7 iAU","h j o","h jo"},
        myo={"m j O:","m jo","m j o","m iAU","m j o","m jo"},
        ryo={"l0 j O:","r jo","r j o","l iAU","r j o","r jo"},
        gyo={"gh j O:","g jo","G j o","k 7 iAU","G j o","g jo"},
        jo={"dZ O:","c o","D j o","ts\\ iAU","dZ o","z o"},
        byo={"bh j O:","b jo","b j o","p iAU","b j o","b jo"},
        pyo={"p j O:","p jo","p j o","p_h iAU","p j o","p jo"},
        n={"n","Np","n","@N","N","Np"},
        ltu={"Sil","Sil","Sil","Sil","Sil","Sil"},
        tye={"t j e","t je","t j e","t_h iE_r","t j e","t je"},
        dye={"d j e","d je","d j e","t iE_r","d j e","d je"},
        pye={"p j e","p je","p j e","p_h iE_r","p j e","p je"},
        tya={"t j a","t ja","t j a","t_h i a","t j a","t ja"},
        dya={"d j a","d ja","d j a","t ia","d j a","d ja"},
        fya={"f y a","h ja","f j a","f o ia","f j a","h ja"},
        tyu={"t j U","t ju","t j u","t_h i @U","t j u","t ju"},
        dyu={"d j U","d ju","d j u","t i@U","d j u","d ju"},
        fyu={"f j U","h ju","f j u","f o i@U","f j u","h ju"},
        tyo={"t j O:","t jo","t j o","t_h iAU","t j o","t jo"},
        dyo={"d j O:","d jo","d j o","t iAU","d j o","d jo"},
        ["ー"]={"-","-","-","-","-","-"}}
    dict = setmetatable(dict,{__index={
        ["ア"]=dict.a,["イ"]=dict.i,["ウ"]=dict.u,["エ"]=dict.e,["オ"]=dict.o,
        ["カ"]=dict.ka,["キ"]=dict.ki,["ク"]=dict.ku,["ケ"]=dict.ke,["コ"]=dict.ko,
        ["サ"]=dict.sa,["シ"]=dict.shi,["ス"]=dict.su,["セ"]=dict.se,["ソ"]=dict.so,
        ["タ"]=dict.ta,["チ"]=dict.chi,["ツ"]=dict.tsu,["テ"]=dict.te,["ト"]=dict.to,
        ["ナ"]=dict.na,["ニ"]=dict.ni,["ヌ"]=dict.nu,["ネ"]=dict.ne,["ノ"]=dict.no,
        ["ハ"]=dict.ha,["ヒ"]=dict.hi,["フ"]=dict.fu,["ヘ"]=dict.he,["ホ"]=dict.ho,
        ["マ"]=dict.ma,["ミ"]=dict.mi,["ム"]=dict.mu,["メ"]=dict.me,["モ"]=dict.mo,
        ["ラ"]=dict.ra,["リ"]=dict.ri,["ル"]=dict.ru,["レ"]=dict.re,["ロ"]=dict.ro,
        ["ガ"]=dict.ga,["ギ"]=dict.gi,["グ"]=dict.gu,["ゲ"]=dict.ge,["ゴ"]=dict.go,
        ["ザ"]=dict.za,["ジ"]=dict.ji,["ズ"]=dict.zu,["ゼ"]=dict.ze,["ゾ"]=dict.zo,
        ["ダ"]=dict.da,["ヂ"]=dict.ji,["ヅ"]=dict.zu,["デ"]=dict.de,["ド"]=dict["do"],
        ["バ"]=dict.ba,["ビ"]=dict.bi,["ブ"]=dict.bu,["ベ"]=dict.be,["ボ"]=dict.bo,
        ["パ"]=dict.pa,["ピ"]=dict.pi,["プ"]=dict.pu,["ペ"]=dict.pe,["ポ"]=dict.po,
        ["ヤ"]=dict.ya,["ユ"]=dict.yu,["ヨ"]=dict.yo,
        ["ワ"]=dict.wa,["ヰ"]=dict.wi,["ヱ"]=dict.we,["ヲ"]=dict.o,
        ["あ"]=dict.a,["い"]=dict.i,["う"]=dict.u,["え"]=dict.e,["お"]=dict.o,
        ["か"]=dict.ka,["き"]=dict.ki,["く"]=dict.ku,["け"]=dict.ke,["こ"]=dict.ko,
        ["さ"]=dict.sa,["し"]=dict.shi,["す"]=dict.su,["せ"]=dict.se,["そ"]=dict.so,
        ["た"]=dict.ta,["ち"]=dict.chi,["つ"]=dict.tsu,["て"]=dict.te,["と"]=dict.to,
        ["な"]=dict.na,["に"]=dict.ni,["ぬ"]=dict.nu,["ね"]=dict.ne,["の"]=dict.no,
        ["は"]=dict.ha,["ひ"]=dict.hi,["ふ"]=dict.fu,["へ"]=dict.he,["ほ"]=dict.ho,
        ["ま"]=dict.ma,["み"]=dict.mi,["む"]=dict.mu,["め"]=dict.me,["も"]=dict.mo,
        ["ら"]=dict.ra,["り"]=dict.ri,["る"]=dict.ru,["れ"]=dict.re,["ろ"]=dict.ro,
        ["が"]=dict.ga,["ぎ"]=dict.gi,["ぐ"]=dict.gu,["げ"]=dict.ge,["ご"]=dict.go,
        ["ざ"]=dict.za,["じ"]=dict.ji,["ず"]=dict.zu,["ぜ"]=dict.ze,["ぞ"]=dict.zo,
        ["だ"]=dict.da,["ぢ"]=dict.ji,["づ"]=dict.zu,["で"]=dict.de,["ど"]=dict["do"],
        ["ば"]=dict.ba,["び"]=dict.bi,["ぶ"]=dict.bu,["べ"]=dict.be,["ぼ"]=dict.bo,
        ["ぱ"]=dict.pa,["ぴ"]=dict.pi,["ぷ"]=dict.pu,["ぺ"]=dict.pe,["ぽ"]=dict.po,
        ["や"]=dict.ya,["ゆ"]=dict.yu,["よ"]=dict.yo,
        ["わ"]=dict.wa,["ゐ"]=dict.wi,["ゑ"]=dict.we,["を"]=dict.o,
        ["ぁ"]=dict.a,["ぃ"]=dict.i,["ぅ"]=dict.u,["ぇ"]=dict.e,["ぉ"]=dict.o,
        ["ゃ"]=dict.ya,["ゅ"]=dict.yu,["ょ"]=dict.yo,["ゎ"]=dict.wa,
        ["ァ"]=dict.a,["ィ"]=dict.i,["ゥ"]=dict.u,["ェ"]=dict.e,["ォ"]=dict.o,
        ["ャ"]=dict.ya,["ュ"]=dict.yu,["ョ"]=dict.yo,["ヮ"]=dict.wa,
        ["ヵ"]=dict.ka,["ヶ"]=dict.ke,["ヴ"]=dict.bu,["っ"]=dict.ltu,["ッ"]=dict.ltu,
        ["ファ"]=dict.fa,["ツァ"]=dict.tsa,["ふぁ"]=dict.fa,["つぁ"]=dict.tsa,
        ["フぁ"]=dict.fa,["ツぁ"]=dict.tsa,["ふァ"]=dict.fa,["つァ"]=dict.tsa,
        ["ウィ"]=dict.wi,["スィ"]=dict.si,["ズィ"]=dict.ji,["ツィ"]=dict.chi,
        ["ティ"]=dict.ti,["ディ"]=dict.di,["フィ"]=dict.fi,
        ["うぃ"]=dict.wi,["すぃ"]=dict.si,["ずぃ"]=dict.ji,["つぃ"]=dict.chi,
        ["てぃ"]=dict.ti,["でぃ"]=dict.di,["ふぃ"]=dict.fi,
        ["ウぃ"]=dict.wi,["スぃ"]=dict.si,["ズぃ"]=dict.ji,["ツぃ"]=dict.chi,
        ["テぃ"]=dict.ti,["デぃ"]=dict.di,["フぃ"]=dict.fi,
        ["うィ"]=dict.wi,["すィ"]=dict.si,["ずィ"]=dict.ji,["つィ"]=dict.chi,
        ["てィ"]=dict.ti,["でィ"]=dict.di,["ふィ"]=dict.fi,
        ["トゥ"]=dict.tu,["ドゥ"]=dict.du,["とぅ"]=dict.tu,["どぅ"]=dict.du,
        ["トぅ"]=dict.tu,["ドぅ"]=dict.du,["とゥ"]=dict.tu,["どゥ"]=dict.du,
        ["イェ"]=dict.ye,["ウェ"]=dict.we,["キェ"]=dict.kye,["シェ"]=dict.she,
        ["チェ"]=dict.che,["ツェ"]=dict.che,["テェ"]=dict.tye,["ニェ"]=dict.nye,
        ["ヒェ"]=dict.hye,["ミェ"]=dict.mye,["リェ"]=dict.rye,["ギェ"]=dict.gye,
        ["ジェ"]=dict.ze,["デェ"]=dict.dye,["ビェ"]=dict.bye,["ピェ"]=dict.pye,["フェ"]=dict.fe,
        ["いぇ"]=dict.ye,["うぇ"]=dict.we,["きぇ"]=dict.kye,["しぇ"]=dict.she,
        ["ちぇ"]=dict.che,["つぇ"]=dict.che,["てぇ"]=dict.tye,["にぇ"]=dict.nye,
        ["ひぇ"]=dict.hye,["みぇ"]=dict.mye,["りぇ"]=dict.rye,["ぎぇ"]=dict.gye,
        ["じぇ"]=dict.ze,["でぇ"]=dict.dye,["びぇ"]=dict.bye,["ぴぇ"]=dict.pye,["ふぇ"]=dict.fe,
        ["イぇ"]=dict.ye,["ウぇ"]=dict.we,["キぇ"]=dict.kye,["シぇ"]=dict.she,
        ["チぇ"]=dict.che,["ツぇ"]=dict.che,["テぇ"]=dict.tye,["ニぇ"]=dict.nye,
        ["ヒぇ"]=dict.hye,["ミぇ"]=dict.mye,["リぇ"]=dict.rye,["ギぇ"]=dict.gye,
        ["ジぇ"]=dict.ze,["デぇ"]=dict.dye,["ビぇ"]=dict.bye,["ピぇ"]=dict.pye,["フぇ"]=dict.fe,
        ["いェ"]=dict.ye,["うェ"]=dict.we,["きェ"]=dict.kye,["しェ"]=dict.she,
        ["ちェ"]=dict.che,["つェ"]=dict.che,["てェ"]=dict.tye,["にェ"]=dict.nye,
        ["ひェ"]=dict.hye,["みェ"]=dict.mye,["りェ"]=dict.rye,["ぎェ"]=dict.gye,
        ["じェ"]=dict.ze,["でェ"]=dict.dye,["びェ"]=dict.bye,["ぴェ"]=dict.pye,["ふェ"]=dict.fe,
        ["ウォ"]=dict.wo,["ツォ"]=dict.tso,["フォ"]=dict.fo,["うぉ"]=dict.wo,["つぉ"]=dict.tso,["ふぉ"]=dict.fo,
        ["ウぉ"]=dict.wo,["ツぉ"]=dict.tso,["フぉ"]=dict.fo,["うォ"]=dict.wo,["つォ"]=dict.tso,["ふォ"]=dict.fo,
        ["キャ"]=dict.kya,["シャ"]=dict.sha,["チャ"]=dict.tsa,["テャ"]=dict.tya,["ニャ"]=dict.nya,
        ["ヒャ"]=dict.hya,["ミャ"]=dict.mya,["リャ"]=dict.rya,["ギャ"]=dict.gya,["ジャ"]=dict.za,
        ["デャ"]=dict.dya,["ビャ"]=dict.bya,["ピャ"]=dict.pya,["フャ"]=dict.hya,
        ["きゃ"]=dict.kya,["しゃ"]=dict.sha,["ちゃ"]=dict.tsa,["てゃ"]=dict.tya,["にゃ"]=dict.nya,
        ["ひゃ"]=dict.hya,["みゃ"]=dict.mya,["りゃ"]=dict.rya,["ぎゃ"]=dict.gya,["じゃ"]=dict.za,
        ["でゃ"]=dict.dya,["びゃ"]=dict.bya,["ぴゃ"]=dict.pya,["ふゃ"]=dict.hya,
        ["キゃ"]=dict.kya,["シゃ"]=dict.sha,["チゃ"]=dict.tsa,["テゃ"]=dict.tya,["ニゃ"]=dict.nya,
        ["ヒゃ"]=dict.hya,["ミゃ"]=dict.mya,["リゃ"]=dict.rya,["ギゃ"]=dict.gya,["ジゃ"]=dict.za,
        ["デゃ"]=dict.dya,["ビゃ"]=dict.bya,["ピゃ"]=dict.pya,["フゃ"]=dict.hya,
        ["きャ"]=dict.kya,["しャ"]=dict.sha,["ちャ"]=dict.tsa,["てャ"]=dict.tya,["にャ"]=dict.nya,
        ["ひャ"]=dict.hya,["みャ"]=dict.mya,["りャ"]=dict.rya,["ぎャ"]=dict.gya,["じャ"]=dict.za,
        ["でャ"]=dict.dya,["びャ"]=dict.bya,["ぴャ"]=dict.pya,["ふャ"]=dict.hya,
        ["キュ"]=dict.kyu,["シュ"]=dict.shu,["チュ"]=dict.tsu,["テュ"]=dict.tyu,["ニュ"]=dict.nyu,
        ["ヒュ"]=dict.hyu,["ミュ"]=dict.myu,["リュ"]=dict.ryu,["ギュ"]=dict.gyu,["ジュ"]=dict.zu,
        ["デュ"]=dict.dyu,["ビュ"]=dict.byu,["ピュ"]=dict.pyu,["フュ"]=dict.hyu,
        ["きゅ"]=dict.kyu,["しゅ"]=dict.shu,["ちゅ"]=dict.tsu,["てゅ"]=dict.tyu,["にゅ"]=dict.nyu,
        ["ひゅ"]=dict.hyu,["みゅ"]=dict.myu,["りゅ"]=dict.ryu,["ぎゅ"]=dict.gyu,["じゅ"]=dict.zu,
        ["でゅ"]=dict.dyu,["びゅ"]=dict.byu,["ぴゅ"]=dict.pyu,["ふゅ"]=dict.hyu,
        ["キゅ"]=dict.kyu,["シゅ"]=dict.shu,["チゅ"]=dict.tsu,["テゅ"]=dict.tyu,["ニゅ"]=dict.nyu,
        ["ヒゅ"]=dict.hyu,["ミゅ"]=dict.myu,["リゅ"]=dict.ryu,["ギゅ"]=dict.gyu,["ジゅ"]=dict.zu,
        ["デゅ"]=dict.dyu,["ビゅ"]=dict.byu,["ピゅ"]=dict.pyu,["フゅ"]=dict.hyu,
        ["きュ"]=dict.kyu,["しュ"]=dict.shu,["ちュ"]=dict.tsu,["てュ"]=dict.tyu,["にュ"]=dict.nyu,
        ["ひュ"]=dict.hyu,["みュ"]=dict.myu,["りュ"]=dict.ryu,["ぎュ"]=dict.gyu,["じュ"]=dict.zu,
        ["でュ"]=dict.dyu,["びュ"]=dict.byu,["ぴュ"]=dict.pyu,["ふュ"]=dict.hyu,
        ["キョ"]=dict.kyo,["ショ"]=dict.sho,["チョ"]=dict.tso,["テョ"]=dict.tyo,
        ["ニョ"]=dict.nyo,["ヒョ"]=dict.hyo,["ミョ"]=dict.myo,["リョ"]=dict.ryo,
        ["ギョ"]=dict.gyo,["ジョ"]=dict.zo,["デョ"]=dict.dyo,["ビョ"]=dict.byo,["ピョ"]=dict.pyo,
        ["きょ"]=dict.kyo,["しょ"]=dict.sho,["ちょ"]=dict.tso,["てょ"]=dict.tyo,
        ["にょ"]=dict.nyo,["ひょ"]=dict.hyo,["みょ"]=dict.myo,["りょ"]=dict.ryo,
        ["ぎょ"]=dict.gyo,["じょ"]=dict.zo,["でょ"]=dict.dyo,["びょ"]=dict.byo,["ぴょ"]=dict.pyo,
        ["キょ"]=dict.kyo,["シょ"]=dict.sho,["チょ"]=dict.tso,["テょ"]=dict.tyo,
        ["ニょ"]=dict.nyo,["ヒょ"]=dict.hyo,["ミょ"]=dict.myo,["リょ"]=dict.ryo,
        ["ギょ"]=dict.gyo,["ジょ"]=dict.zo,["デょ"]=dict.dyo,["ビょ"]=dict.byo,["ピょ"]=dict.pyo,
        ["きョ"]=dict.kyo,["しョ"]=dict.sho,["ちョ"]=dict.tso,["てョ"]=dict.tyo,
        ["にョ"]=dict.nyo,["ひョ"]=dict.hyo,["みョ"]=dict.myo,["りョ"]=dict.ryo,
        ["ぎョ"]=dict.gyo,["じョ"]=dict.zo,["でョ"]=dict.dyo,["びョ"]=dict.byo,["ぴョ"]=dict.pyo,
        ["ん"]=dict.n,ltsu=dict.ltu,xtu=dict.ltu,xtsu=dict.ltu
    }})
    if f == 0 then
        for v in lyrics:gmatch("%S+") do
            if v == "-" or v:find("^[a-z]+$") then lyricList[#lyricList + 1] = v end
        end
    else
        local smallKana = {
            ["ィ"] = "ウうスすズずテてデで", ["ぃ"] = "ウうスすズずテてデで",
            ["ェ"] = "ツつフふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり", ["ぇ"] = "ツつフふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり",
            ["ャ"] = "フふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり", ["ゃ"] = "フふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり",
            ["ュ"] = "フふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり", ["ゅ"] = "フふキきギぎシしジじチちテてデでニにヒひビびピぴミみリり",
            ["ョ"] = "キきギぎシしジじチちテてデでニにヒひビびピぴミみリり", ["ょ"] = "キきギぎシしジじチちテてデでニにヒひビびピぴミみリり",
            ["ァ"] = "ツつフふ", ["ぁ"] = "ツつフふ", ["ォ"] = "ツつフふ", ["ぉ"] = "ツつフふ",
            ["ゥ"] = "トとドど", ["ぅ"] = "トとドど"
        }
        local prev, pos = nil, 1
        while pos <= #lyrics do
            local byte1 = lyrics:byte(pos)
            local len, v = 1, (byte1 == string.byte("-")) and "-" or ""
            if byte1 == 0xE3 then
                local byte2, byte3 = lyrics:byte(pos+1), lyrics:byte(pos+2)
                if byte2 and byte3 and (byte2 >= 0x81 and byte2 <= 0x83) and byte3 >= 0x80 and byte3 <= 0xBF then
                    len, v = 3, lyrics:sub(pos, pos+2)
                end
            end
            if v ~= "" and v ~= " " then
                if v == "-" then
                    lyricList[#lyricList+1], prev = v, nil 
                else
                    local allowedChars = smallKana[v]
                    if allowedChars and prev and allowedChars:find(prev, 1, true) then
                        lyricList[#lyricList] = prev .. v
                        prev = lyricList[#lyricList]
                    else
                        lyricList[#lyricList+1], prev = v, v 
                    end
                end
            end
            pos = pos + len
        end
    end
    for i, lyric in ipairs(lyricList) do
        phonemeList[i] = lyric == "-" and "-" or dict[lyric][idx-1] or def
    end
    return lyricList, phonemeList
end